version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo $AWS_ACCOUNT_ID in $AWS_REGION
      - docker build -t app-container-registry:blueproject .
      - docker tag app-container-registry:blueproject $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/app-container-registry:blueproject
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/app-container-registry:blueproject