version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - npm install
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Building application
      - docker build -t app-container-registry:latest .
      - docker tag app-container-registry:latest app-container-registry:latest
  post_build:
    commands:
      - echo Pushing the Docker images...
      - docker push app-container-registry:latest
      - echo Writing image definitions file...
      - printf '[{"name":"nodejs-docker","imageUri":"%s"}]' app-container-registry:latest > imagedefinitions.json
cache:
    paths:
      - ~/.npm
      - /var/lib/docker/**/*